spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  webflux:
    hiddenmethod:
      filter:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"